# Generated by Django 4.1.5 on 2023-01-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='accuracy',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='min_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='buyout_price',
            field=models.FloatField(),
        ),
    ]
