# Generated by Django 4.1.5 on 2023-01-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0002_item_accuracy_item_min_price_alter_item_buyout_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='buyout_price',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
