# Generated by Django 4.1.5 on 2023-01-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0004_alter_item_accuracy'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zero_price_items', models.BooleanField()),
                ('max_prod_amount', models.IntegerField()),
            ],
        ),
    ]
