# Generated by Django 4.1.5 on 2023-01-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0006_rename_max_prod_amount_tablesetting_max_item_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablesetting',
            old_name='max_item_amount',
            new_name='max_items_amount',
        ),
    ]
