# Generated by Django 4.1.5 on 2023-01-29 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0008_blacklist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blacklist',
            old_name='name',
            new_name='item',
        ),
    ]
